#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

import zulip

usage = """ get-messages (--anchor <message_id> | --use-first-unread-anchor) \
--num-before <amount> --num-after <amount> [--narrow <narrow_dict>]

Example: get-messages --anchor=42 --num-before=3 --num-after=14 --narrow=\
'[{"operator": "sender", "operand": "iago@zulip.com"}]'
"""


parser = zulip.add_default_arguments(argparse.ArgumentParser(usage=usage))
parser.add_argument('--anchor', type=int)
parser.add_argument('--use-first-unread-anchor', action='store_true')
parser.add_argument('--num-before', type=int, required=True)
parser.add_argument('--num-after', type=int, required=True)
parser.add_argument('--narrow')
options = parser.parse_args()

client = zulip.init_from_options(options)

print(client.get_messages({
    'anchor': options.anchor,
    'use_first_unread_anchor': options.use_first_unread_anchor,
    'num_before': options.num_before,
    'num_after': options.num_after,
    'narrow': options.narrow,
}))
