#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import argparse

usage = """list-subscriptions [options]

Prints out a list of the user's subscriptions.

Example: list-subscriptions

Specify your Zulip API credentials and server in a ~/.zuliprc file or using the options.
"""

import zulip

parser = zulip.add_default_arguments(argparse.ArgumentParser(usage=usage))
options = parser.parse_args()

client = zulip.init_from_options(options)

print(client.list_subscriptions())
