#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

import zulip

usage = """realm-emoji [options]

Example: realm-emoji
"""

parser = zulip.add_default_arguments(argparse.ArgumentParser(usage=usage))
options = parser.parse_args()

client = zulip.init_from_options(options)

print(client.get_realm_emoji())
