#!/usr/bin/env bash

set -ev

wget https://github.com/houstondatavis/slack-export/archive/master.zip

mv master.zip slack-export-master.zip
zulip/integrations/slack/slackdata2zulipdata.py $PWD/slack-export-master.zip

mv zulip_data.tar.gz $HOME
cd
git clone --depth=50 --branch=test-slack-importer https://github.com/rheaparekh/zulip.git
cd zulip
mv ../zulip_data.tar.gz .
tar xf zulip_data.tar.gz

./tools/travis/setup-backend
source tools/travis/activate-venv
./manage.py import --destroy-rebuild-database $PWD/zulip_data
