#!/bin/bash

sed -i "s|zulip/python-zulip-api.git@0.3.4|$TRAVIS_PULL_REQUEST_SLUG.git@$TRAVIS_PULL_REQUEST_BRANCH|" requirements/common.txt
sed -i "s|zulip/python-zulip-api.git@0.3.4|$TRAVIS_PULL_REQUEST_SLUG.git@$TRAVIS_PULL_REQUEST_BRANCH|" requirements/dev_lock.txt
sed -i "s|zulip/python-zulip-api.git@0.3.4|$TRAVIS_PULL_REQUEST_SLUG.git@$TRAVIS_PULL_REQUEST_BRANCH|" requirements/prod_lock.txt

./tools/travis/setup-backend

source tools/travis/activate-venv
echo "Test suite is running under $(python --version)."

set -e
set -x

./tools/test-api
