#!/usr/bin/env python

from server_lib.test_handler import handle_input_and_run_tests_for_package

if __name__ == '__main__':
    handle_input_and_run_tests_for_package('Botserver', ['zulip_botserver'])
