#!/usr/bin/env python

import coverage
import os
import sys
import unittest

from importlib import import_module

def run_all():
    TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
    ROOT_DIR = os.path.abspath(os.path.join(TOOLS_DIR, '..'))
    BOTS_DIR = os.path.join(ROOT_DIR, 'zulib_bots')
    sys.path.insert(0, BOTS_DIR)

    cov = coverage.Coverage(config_file="tools/.coveragerc")
    cov.start()

    module = import_module('zulip_bots.lib_tests')
    suite = unittest.defaultTestLoader.loadTestsFromModule(module)

    suite = unittest.TestSuite([suite])
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    if result.failures or result.errors:
        sys.exit(1)

    cov.stop()
    cov.data_suffix = False  # Disable suffix so that filename is .coverage
    cov.save()
    cov.html_report()
    print("HTML report saved under directory 'htmlcov'.")

if __name__ == '__main__':
    run_all()
