#!/usr/bin/env bash

set -ev

CURRENT_DIR=$(dirname "$0")
cd "$CURRENT_DIR"
cd ..

if [ "$TEST_SUITE" == "linter" ]
then
    tools/lint
else
    python -m unittest discover -v zulip_botserver
    tools/test-bots
fi
